### ISSUE TITLE
Faltam-te moldes neste repo

### ISSUE THREAD

**Issue by gagomes** [falsovsky/advent2022#1]
Sabias que o Harry Reems morreu?

**Comment by falsovsky** [comment]
Uiiii moldes. Quando tiro os moldes é me muito *doloroso*.

**Comment by falsovsky** [comment]
Nao conhecia essa personagem.

**Comment by falsovsky** [comment]
Advento de hoje ta feito.

**Comment by gagomes** [comment]
> Nao conhecia essa personagem.

Conhecias sim, o actor principal do classico garganta funda
